# Generated by Django 3.1.6 on 2021-02-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_auto_20210219_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='ended_on',
            field=models.DateField(null=True),
        ),
    ]
